### ISSUE TITLE
Biographies which are not possible to get pageviews

### ISSUE THREAD

**Issue by crcandia** [crisjf/johnny5#10]
There are a bunch of biographies where is not possible to get the pageviews, and the pageviews are available in the apps (grok and rest). 
<img width="1110" alt="screen shot 2017-07-21 at 4 46 05 pm" src="https://user-images.githubusercontent.com/18038488/28481965-481b00ca-6e34-11e7-8bbe-0ee7ebde5951.png">

<img width="1890" alt="screen shot 2017-07-21 at 4 48 25 pm" src="https://user-images.githubusercontent.com/18038488/28482000-76056f2a-6e34-11e7-8916-ed23cf80eff6.png">

**Comment by crisjf** [comment]
This seems to be working now with the latest push to the pageviews function
